export const mockBills: Bill[] = [
    {
        id: '1',
        title: 'School Tuition',
        category: 'Education',
        amount: 500,
        dueDate: 'Jan 25, 2026',
        daysInfo: '5d overdue',
        status: 'overdue',
        isRecurring: false,
    },
    {
        id: '2',
        title: 'Rent Payment',
        category: 'Housing',
        amount: 800,
        dueDate: 'Feb 1, 2026',
        daysInfo: '2d left',
        status: 'urgent',
        isRecurring: true,
    },
    {
        id: '3',
        title: 'Electricity Bill',
        category: 'Utilities',
        amount: 150,
        dueDate: 'Feb 5, 2026',
        daysInfo: '6d left',
        status: 'upcoming',
        isRecurring: true,
    },
    {
        id: '4',
        title: 'Internet Service',
        category: 'Utilities',
        amount: 60,
        dueDate: 'Feb 10, 2026',
        daysInfo: '11d left',
        status: 'upcoming',
        isRecurring: true,
    },
    {
        id: '4',
        title: 'Internet Service',
        category: 'Utilities',
        amount: 60,
        dueDate: 'Feb 10, 2026',
        daysInfo: '11d left',
        status: 'paid',
        isRecurring: true,
    },
];